# =============================================================
# Mosquitto MQTT Broker Configuration
# =============================================================

# --- General ---
user mosquitto
allow_anonymous false
password_file /mosquitto/config/pwfile

# --- Listener ---
listener 1883

# --- Persistence ---
persistence true
persistence_location /mosquitto/data/mosquitto

# --- Logging ---
log_dest file /mosquitto/log/saimosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_type subscribe
log_type unsubscribe
