# Pooja room WLED light — morning schedule (4:45 AM on, 6:30 AM off)
- alias: Pooja_morning_On
  description: Pooja_morning_On
  trigger:
  - platform: time
    at: '04:45:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      color_temp: 338
      brightness: 255
    target:
      entity_id: light.wled
  mode: single
- alias: Pooja_morning_Off
  description: Pooja_morning_Off
  trigger:
  - platform: time
    at: '06:30:00'
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.wled
  mode: single
